language: python
python:
  - "3.8"
# command to install dependencies

services:
  - docker

before_script: pip install docker-compose

before_install:
  - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin

install:
  - pip install -r requirements.txt
script:
  - docker-compose run app sh -c "python manage.py test && flake8"
